apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  # node-postgres-2
spec:
  selector:
    app: {{ .Values.deployment.labels.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.port }}
  type: {{ .Values.service.type }}